### ISSUE TITLE
Profile Information Issue

### ISSUE THREAD

**Issue by builtbyjonas** [clqu/clqu.live#1]
Help pls i added my id into the vcodes api link and im on the discord server but the profile information are still not working. how can i fix it? pls help @clqu
![grafik](https://user-images.githubusercontent.com/81481526/157809204-fb57e62f-d8b3-45f1-95e7-64ba5d50477c.png)

**Comment by clqu** [comment]
Because vCodes is a private api, you should use different api for this.
